<?php
/* @var $this FloorController */
/* @var $model Floor */

$this->breadcrumbs=array(
	'Floors'=>array('index'),
	$model->floor_id,
);

$this->menu=array(
	array('label'=>'List Floor', 'url'=>array('index')),
	array('label'=>'Create Floor', 'url'=>array('create')),
	array('label'=>'Update Floor', 'url'=>array('update', 'id'=>$model->floor_id)),
	array('label'=>'Delete Floor', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->floor_id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Floor', 'url'=>array('admin')),
);
?>

<h1>View Floor #<?php echo $model->floor_id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'floor_id',
		'building_id',
		'vacancy_info',
		'move_in_date',
		'preceding_user',
		'preceding_details',
		'preceding_check_datetime',
		'vacant_schedule',
		'floor_down',
		'floor_up',
		'roomname',
		'maisonette_type',
		'short_term_rent',
		'type_of_use',
		'area_ping',
		'area_m',
		'area_net',
		'calculation_method',
		'payment_by_installments',
		'payment_by_installments_note',
		'floor_partition',
		'rent_unit_price_opt',
		'rent_unit_price',
		'total_rent_price',
		'unit_condo_fee_opt',
		'unit_condo_fee',
		'total_condo_fee',
		'deposit_opt',
		'deposit_month',
		'deposit',
		'total_deposit',
		'key_money_opt',
		'key_money_month',
		'repayment_opt',
		'repayment_reason',
		'repayment_amt',
		'repayment_amt_opt',
		'renewal_fee_opt',
		'renewal_fee_reason',
		'renewal_fee_recent',
		'repayment_notes',
		'notice_of_cancellation',
		'contract_period_opt',
		'contract_period_duration',
		'air_conditioning_facility_type',
		'air_conditioning_details',
		'air_conditioning_time_used',
		'number_of_air_conditioning',
		'optical_cable',
		'oa_type',
		'oa_height',
		'floor_material',
		'ceiling_height',
		'electric_capacity',
		'separate_toilet_by_gender',
		'toilet_location',
		'washlet',
		'toilet_cleaning',
		'notes',
		'floor_source_id',
		'update_person_in_charge',
		'property_confirmation_person',
		'is_condominium_ownership',
		'ownership_type',
		'management_type',
		'owner_company_name',
		'company_tel',
		'person_in_charge1',
		'person_in_charge2',
		'charge',
	),
)); ?>
